"""3.10.1

Revision ID: 8610e2276677
Revises: c3d6d712e79c
Create Date: 2025-10-10 23:02:49.536670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8610e2276677'
down_revision = 'c3d6d712e79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
