"""3.10.1

Revision ID: 9c64570e5001
Revises: e597a93ff90c
Create Date: 2025-10-11 16:26:20.482396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c64570e5001'
down_revision = 'e597a93ff90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ross_panel_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('platform', sa.String(length=255), nullable=False, comment='平台名称'),
    sa.Column('key_value', sa.String(length=255), nullable=False, comment='key'),
    sa.Column('useapp_name', sa.String(length=255), nullable=False, comment='使用的app名称'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_value')
    )
    op.create_table('ross_panel_app_update',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('app_name', sa.String(length=255), nullable=False, comment='app名称'),
    sa.Column('version', sa.String(length=255), nullable=False, comment='版本号'),
    sa.Column('update_json', sa.String(length=255), nullable=False, comment='更新json'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='更新内容'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ross_panel_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('app_name', sa.String(length=255), nullable=False, comment='app名称'),
    sa.Column('text', sa.String(length=255), nullable=False, comment='反馈内容'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ross_panel_feedback')
    op.drop_table('ross_panel_app_update')
    op.drop_table('ross_panel_api_keys')
    # ### end Alembic commands ###
