"""3.10.1

Revision ID: c3d6d712e79c
Revises: 0eb5034e83f8
Create Date: 2025-10-10 22:58:07.971369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3d6d712e79c'
down_revision = '0eb5034e83f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_console')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_console',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
