"""3.10.1

Revision ID: cbf365883c44
Revises: 
Create Date: 2025-10-09 11:45:04.037814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbf365883c44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vadmin_auth_user_name', table_name='vadmin_auth_user')
    op.drop_index('ix_vadmin_auth_user_telephone', table_name='vadmin_auth_user')
    op.drop_table('vadmin_auth_user')
    op.drop_index('ix_vadmin_auth_menu_perms', table_name='vadmin_auth_menu')
    op.drop_table('vadmin_auth_menu')
    op.drop_index('ix_vadmin_system_settings_config_key', table_name='vadmin_system_settings')
    op.drop_table('vadmin_system_settings')
    op.drop_index('idx_code_id', table_name='ross_activation_records')
    op.drop_index('idx_status', table_name='ross_activation_records')
    op.drop_index('idx_user_id', table_name='ross_activation_records')
    op.drop_index('uk_user_device', table_name='ross_activation_records')
    op.drop_table('ross_activation_records')
    op.drop_table('ross_question')
    op.drop_table('ross_answer')
    op.drop_index('idx_activated_by', table_name='ross_activation_codes')
    op.drop_index('idx_expires_at', table_name='ross_activation_codes')
    op.drop_index('idx_status', table_name='ross_activation_codes')
    op.drop_index('uk_code', table_name='ross_activation_codes')
    op.drop_table('ross_activation_codes')
    op.drop_table('vadmin_auth_user_depts')
    op.drop_index('ix_vadmin_auth_role_name', table_name='vadmin_auth_role')
    op.drop_index('ix_vadmin_auth_role_role_key', table_name='vadmin_auth_role')
    op.drop_table('vadmin_auth_role')
    op.drop_index('ix_vadmin_auth_dept_dept_key', table_name='vadmin_auth_dept')
    op.drop_index('ix_vadmin_auth_dept_name', table_name='vadmin_auth_dept')
    op.drop_table('vadmin_auth_dept')
    op.drop_table('vadmin_resource_images')
    op.drop_index('ix_vadmin_record_login_telephone', table_name='vadmin_record_login')
    op.drop_table('vadmin_record_login')
    op.drop_index('ix_vadmin_help_issue_category_name', table_name='vadmin_help_issue_category')
    op.drop_index('ix_vadmin_help_issue_category_platform', table_name='vadmin_help_issue_category')
    op.drop_table('vadmin_help_issue_category')
    op.drop_index('ix_vadmin_help_issue_title', table_name='vadmin_help_issue')
    op.drop_table('vadmin_help_issue')
    op.drop_table('vadmin_auth_role_depts')
    op.drop_table('vadmin_record_sms_send')
    op.drop_table('ross_customer_context')
    op.drop_table('vadmin_auth_role_menus')
    op.drop_table('vadmin_auth_user_roles')
    op.drop_index('ix_vadmin_system_dict_type_dict_name', table_name='vadmin_system_dict_type')
    op.drop_index('ix_vadmin_system_dict_type_dict_type', table_name='vadmin_system_dict_type')
    op.drop_table('vadmin_system_dict_type')
    op.drop_index('ix_vadmin_system_dict_details_label', table_name='vadmin_system_dict_details')
    op.drop_index('ix_vadmin_system_dict_details_value', table_name='vadmin_system_dict_details')
    op.drop_table('vadmin_system_dict_details')
    op.drop_index('ix_vadmin_system_settings_tab_classify', table_name='vadmin_system_settings_tab')
    op.drop_index('ix_vadmin_system_settings_tab_tab_name', table_name='vadmin_system_settings_tab')
    op.drop_table('vadmin_system_settings_tab')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vadmin_system_settings_tab',
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='标题'),
    sa.Column('classify', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='分类键'),
    sa.Column('tab_label', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='tab标题'),
    sa.Column('tab_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='tab标识符'),
    sa.Column('hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否隐藏'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置分类表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='系统配置分类表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_system_settings_tab_tab_name', 'vadmin_system_settings_tab', ['tab_name'], unique=True)
    op.create_index('ix_vadmin_system_settings_tab_classify', 'vadmin_system_settings_tab', ['classify'], unique=False)
    op.create_table('vadmin_system_dict_details',
    sa.Column('label', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='字典标签'),
    sa.Column('value', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='字典键值'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='字典状态，是否禁用'),
    sa.Column('is_default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否默认'),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=False, comment='字典排序'),
    sa.Column('dict_type_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联字典类型'),
    sa.Column('remark', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='备注'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['dict_type_id'], ['vadmin_system_dict_type.id'], name='vadmin_system_dict_details_ibfk_1', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典详情表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='字典详情表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_system_dict_details_value', 'vadmin_system_dict_details', ['value'], unique=False)
    op.create_index('ix_vadmin_system_dict_details_label', 'vadmin_system_dict_details', ['label'], unique=False)
    op.create_table('vadmin_system_dict_type',
    sa.Column('dict_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='字典名称'),
    sa.Column('dict_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='字典类型'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='字典状态，是否禁用'),
    sa.Column('remark', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='备注'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典类型表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='字典类型表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_system_dict_type_dict_type', 'vadmin_system_dict_type', ['dict_type'], unique=False)
    op.create_index('ix_vadmin_system_dict_type_dict_name', 'vadmin_system_dict_type', ['dict_name'], unique=False)
    op.create_table('vadmin_auth_user_roles',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['vadmin_auth_role.id'], name='vadmin_auth_user_roles_ibfk_1', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['vadmin_auth_user.id'], name='vadmin_auth_user_roles_ibfk_2', onupdate='RESTRICT', ondelete='CASCADE'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('vadmin_auth_role_menus',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('menu_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['vadmin_auth_menu.id'], name='vadmin_auth_role_menus_ibfk_1', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['vadmin_auth_role.id'], name='vadmin_auth_role_menus_ibfk_2', onupdate='RESTRICT', ondelete='CASCADE'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ross_customer_context',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False, comment='用户ID'),
    sa.Column('input', mysql.VARCHAR(length=1024), nullable=False, comment='输入内容'),
    sa.Column('output', mysql.TEXT(), nullable=False, comment='输出内容'),
    sa.Column('question_progress', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='用户回答问题进度'),
    sa.Column('is_tagged', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已经打过标签'),
    sa.Column('user_tag', mysql.VARCHAR(length=50), server_default=sa.text("'standard_consumer'"), nullable=False, comment='可选值，full_consumer，standard_consumer,small_consumer,agents_consumer,supplier_consumer'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('is_delete', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='客户上下文表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='客户上下文表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vadmin_record_sms_send',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='操作人'),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='发送状态'),
    sa.Column('content', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='发送内容'),
    sa.Column('telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=11), nullable=False, comment='目标手机号'),
    sa.Column('desc', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='失败描述'),
    sa.Column('scene', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='发送场景'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['user_id'], ['vadmin_auth_user.id'], name='vadmin_record_sms_send_ibfk_1', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='短信发送记录表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='短信发送记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('vadmin_auth_role_depts',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['vadmin_auth_dept.id'], name='vadmin_auth_role_depts_ibfk_1', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['vadmin_auth_role.id'], name='vadmin_auth_role_depts_ibfk_2', onupdate='RESTRICT', ondelete='CASCADE'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('vadmin_help_issue',
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='类别'),
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='标题'),
    sa.Column('content', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=False, comment='内容'),
    sa.Column('view_number', mysql.INTEGER(), autoincrement=False, nullable=False, comment='查看次数'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否可见'),
    sa.Column('create_user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='创建人'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['category_id'], ['vadmin_help_issue_category.id'], name='vadmin_help_issue_ibfk_1', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['create_user_id'], ['vadmin_auth_user.id'], name='vadmin_help_issue_ibfk_2', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='常见问题记录表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='常见问题记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_help_issue_title', 'vadmin_help_issue', ['title'], unique=False)
    op.create_table('vadmin_help_issue_category',
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='类别名称'),
    sa.Column('platform', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=8), nullable=False, comment='展示平台'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否可见'),
    sa.Column('create_user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='创建人'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['create_user_id'], ['vadmin_auth_user.id'], name='vadmin_help_issue_category_ibfk_1', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='常见问题类别表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='常见问题类别表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_help_issue_category_platform', 'vadmin_help_issue_category', ['platform'], unique=False)
    op.create_index('ix_vadmin_help_issue_category_name', 'vadmin_help_issue_category', ['name'], unique=False)
    op.create_table('vadmin_record_login',
    sa.Column('telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='手机号'),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否登录成功'),
    sa.Column('platform', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=8), nullable=False, comment='登陆平台'),
    sa.Column('login_method', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=8), nullable=False, comment='认证方式'),
    sa.Column('ip', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='登陆地址'),
    sa.Column('address', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='登陆地点'),
    sa.Column('country', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='国家'),
    sa.Column('province', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='县'),
    sa.Column('city', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='城市'),
    sa.Column('county', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='区/县'),
    sa.Column('operator', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='运营商'),
    sa.Column('postal_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='邮政编码'),
    sa.Column('area_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='地区区号'),
    sa.Column('browser', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='浏览器'),
    sa.Column('system', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='操作系统'),
    sa.Column('response', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='响应信息'),
    sa.Column('request', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='请求信息'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录记录表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='登录记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_record_login_telephone', 'vadmin_record_login', ['telephone'], unique=False)
    op.create_table('vadmin_resource_images',
    sa.Column('filename', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='原图片名称'),
    sa.Column('image_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=500), nullable=False, comment='图片链接'),
    sa.Column('create_user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='创建人'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['create_user_id'], ['vadmin_auth_user.id'], name='vadmin_resource_images_ibfk_1', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='图片素材表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='图片素材表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('vadmin_auth_dept',
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='部门名称'),
    sa.Column('dept_key', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='部门标识'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True, comment='显示排序'),
    sa.Column('desc', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='描述'),
    sa.Column('owner', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='负责人'),
    sa.Column('phone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='联系电话'),
    sa.Column('email', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='邮箱'),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='上级部门'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['vadmin_auth_dept.id'], name='vadmin_auth_dept_ibfk_1', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='部门表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='部门表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_auth_dept_name', 'vadmin_auth_dept', ['name'], unique=False)
    op.create_index('ix_vadmin_auth_dept_dept_key', 'vadmin_auth_dept', ['dept_key'], unique=False)
    op.create_table('vadmin_auth_role',
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='名称'),
    sa.Column('role_key', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='权限字符'),
    sa.Column('data_range', mysql.INTEGER(), autoincrement=False, nullable=False, comment='数据权限范围'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('desc', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='描述'),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否为超级角色'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='角色表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_auth_role_role_key', 'vadmin_auth_role', ['role_key'], unique=False)
    op.create_index('ix_vadmin_auth_role_name', 'vadmin_auth_role', ['name'], unique=False)
    op.create_table('vadmin_auth_user_depts',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['vadmin_auth_dept.id'], name='vadmin_auth_user_depts_ibfk_1', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['vadmin_auth_user.id'], name='vadmin_auth_user_depts_ibfk_2', onupdate='RESTRICT', ondelete='CASCADE'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ross_activation_codes',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('code', mysql.VARCHAR(length=64), nullable=False, comment='激活码'),
    sa.Column('type', mysql.VARCHAR(length=20), server_default=sa.text("'trial'"), nullable=False, comment='类型：trial-试用, personal-个人, team-团队, enterprise-企业'),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'active'"), nullable=False, comment='状态：active-未使用, used-已使用, expired-已过期, revoked-已撤销'),
    sa.Column('user_limit', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='用户数量限制'),
    sa.Column('duration_days', mysql.INTEGER(), server_default=sa.text("'30'"), autoincrement=False, nullable=False, comment='有效期天数'),
    sa.Column('features', mysql.JSON(), nullable=True, comment='功能权限配置'),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True, comment='创建者'),
    sa.Column('activated_by', mysql.VARCHAR(length=100), nullable=True, comment='激活者'),
    sa.Column('activated_datatime', mysql.DATETIME(), nullable=True, comment='激活时间'),
    sa.Column('create_datatime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('expires_datetime', mysql.DATETIME(), sa.Computed('((`create_datatime` + interval `duration_days` day))', persisted=True), nullable=True, comment='过期时间'),
    sa.Column('update_datatime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='激活码表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='激活码表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uk_code', 'ross_activation_codes', ['code'], unique=True)
    op.create_index('idx_status', 'ross_activation_codes', ['status'], unique=False)
    op.create_index('idx_expires_at', 'ross_activation_codes', ['expires_datetime'], unique=False)
    op.create_index('idx_activated_by', 'ross_activation_codes', ['activated_by'], unique=False)
    op.create_table('ross_answer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='问题ID'),
    sa.Column('next_question', mysql.INTEGER(), autoincrement=False, nullable=True, comment='下一题'),
    sa.Column('answer', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='答案'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='回答表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='回答表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ross_question',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('question', mysql.VARCHAR(length=2048), server_default=sa.text("''"), nullable=False, comment='问题'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='问题表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='问题表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ross_activation_records',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('code_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='激活码id'),
    sa.Column('user_id', mysql.VARCHAR(length=100), nullable=False, comment='用户id'),
    sa.Column('device_id', mysql.VARCHAR(length=100), nullable=True, comment='设备id'),
    sa.Column('device_info', mysql.JSON(), nullable=True, comment='设备信息'),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True, comment='ip地址'),
    sa.Column('activated_datatime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='激活时间'),
    sa.Column('last_verified_datatime', mysql.DATETIME(), nullable=True, comment='最后验证时间'),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'active'"), nullable=False, comment='状态：active-有效, expired-过期, revoked-撤销'),
    sa.PrimaryKeyConstraint('id'),
    comment='激活记录表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='激活记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uk_user_device', 'ross_activation_records', ['user_id', 'device_id'], unique=True)
    op.create_index('idx_user_id', 'ross_activation_records', ['user_id'], unique=False)
    op.create_index('idx_status', 'ross_activation_records', ['status'], unique=False)
    op.create_index('idx_code_id', 'ross_activation_records', ['code_id'], unique=False)
    op.create_table('vadmin_system_settings',
    sa.Column('config_label', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='配置表标签'),
    sa.Column('config_key', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='配置表键'),
    sa.Column('config_value', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='配置表内容'),
    sa.Column('remark', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='备注信息'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('tab_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联tab标签'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['tab_id'], ['vadmin_system_settings_tab.id'], name='vadmin_system_settings_ibfk_1', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='系统配置表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_system_settings_config_key', 'vadmin_system_settings', ['config_key'], unique=True)
    op.create_table('vadmin_auth_menu',
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='名称'),
    sa.Column('icon', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='菜单图标'),
    sa.Column('redirect', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='重定向地址'),
    sa.Column('component', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='前端组件地址'),
    sa.Column('path', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='前端路由地址'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否隐藏'),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=False, comment='排序'),
    sa.Column('menu_type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=8), nullable=False, comment='菜单类型'),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='父菜单'),
    sa.Column('perms', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='权限标识'),
    sa.Column('noCache', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='如果设置为true，则不会被 <keep-alive> 缓存(默认 false)'),
    sa.Column('breadcrumb', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='如果设置为false，则不会在breadcrumb面包屑中显示(默认 true)'),
    sa.Column('affix', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='如果设置为true，则会一直固定在tag项中(默认 false)'),
    sa.Column('noTagsView', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='如果设置为true，则不会出现在tag中(默认 false)'),
    sa.Column('canTo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='设置为true即使hidden为true，也依然可以进行路由跳转(默认 false)'),
    sa.Column('alwaysShow', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='当你一个路由下面的 children 声明的路由大于1个时，自动会变成嵌套的模式，\n    只有一个时，会将那个子路由当做根路由显示在侧边栏，若你想不管路由下面的 children 声明的个数都显示你的根路由，\n    你可以设置 alwaysShow: true，这样它就会忽略之前定义的规则，一直显示根路由(默认 true)'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['vadmin_auth_menu.id'], name='vadmin_auth_menu_ibfk_1', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='菜单表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_auth_menu_perms', 'vadmin_auth_menu', ['perms'], unique=False)
    op.create_table('vadmin_auth_user',
    sa.Column('avatar', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=500), nullable=True, comment='头像'),
    sa.Column('telephone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=11), nullable=False, comment='手机号'),
    sa.Column('email', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='邮箱地址'),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='姓名'),
    sa.Column('nickname', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='昵称'),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='密码'),
    sa.Column('gender', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=8), nullable=True, comment='性别'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否可用'),
    sa.Column('is_reset_password', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否已经重置密码，没有重置的，登陆系统后必须重置密码'),
    sa.Column('last_ip', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True, comment='最后一次登录IP'),
    sa.Column('last_login', mysql.DATETIME(), nullable=True, comment='最近一次登录时间'),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否为工作人员'),
    sa.Column('wx_server_openid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='服务端微信平台openid'),
    sa.Column('is_wx_server_openid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否已有服务端微信平台openid'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='用户表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_vadmin_auth_user_telephone', 'vadmin_auth_user', ['telephone'], unique=False)
    op.create_index('ix_vadmin_auth_user_name', 'vadmin_auth_user', ['name'], unique=False)
    # ### end Alembic commands ###
